name: xmonad-noctis
version: 0.17
synopsis: My xmonad configuration.
license: MIT
author: Noctis
homepage: https://github.com/MartensStijn/xmonad

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints -O2 -j -dynamic

dependencies:
  - base
  - xmonad-contrib >= 0.17

source-dirs: src

executables:
  xmonad:
    main: xmonad.hs
    dependencies:
      - xmonad
      - containers
      - X11 >= 1.10
  xmobar:
    main: xmobar.hs
    dependencies:
      - xmobar
    ghc-options: -rtsopts -threaded -with-rtsopts=-N
